aws_url: "a1i24hje2n1ej1.iot.ap-southeast-1.amazonaws.com"
ca_file_path: "/home/abilash/AWS/IoT/TRL/certs/local_server/AmazonRootCA1.pem"
cert_path: "/home/abilash/AWS/IoT/TRL/certs/local_server/device.pem.crt"
key_path: "/home/abilash/AWS/IoT/TRL/certs/local_server/device.private.key"
client_id: "basicPubSub"
lift_state_topic: "sdk/test/Python"
lift_command_topic: "topic_1"
door_state_topic: "sdk/test/java"
door_command_topic: "topic_2"